import Image from 'next/image';
import Link from 'next/link';

type PageData = {title:string; kicker:string; intro:string; cards:string[]; items?: {title:string; image:string; href:string; alt:string}[]};

const pages: Record<string,PageData> = {
  solutions:{title:'Solutions that belong together.',kicker:'OUR APPROACH',intro:'Zenith designs connected environments where lighting, security, access, climate, entertainment and energy work as one considered system.',cards:['Smart home automation','Intelligent security','Lighting & scenes']},
  'smart-home':{title:'One home. Infinite possibilities.',kicker:'SMART HOME',intro:'A home that responds to the way you live. From a single room to a whole property, Zenith connects the everyday systems that make home feel effortless.',cards:['Lighting & scenes','Climate control','Curtains & blinds']},
  security:{title:'Security that never switches off.',kicker:'SMART SECURITY',intro:'Integrated CCTV, motion detection, monitoring, alerts and access control give you a clear view of what matters, wherever you are.',cards:['24/7 monitoring','Remote viewing','Smart alerts']},
  'smart-lighting':{title:'Set the mood. Before you enter.',kicker:'SMART LIGHTING',intro:'Create scenes, automate schedules and control individual rooms from your phone, wall panel or compatible voice assistant.',cards:['Morning','Relax','Movie']},
  'smart-access':{title:'Leave the keys behind.',kicker:'SMART ACCESS',intro:'Fingerprint, PIN, card and remote access designed around convenience without compromising security.',cards:['Fingerprint access','PIN & card entry','Remote access']},
  'voice-automation':{title:'Just say it.',kicker:'VOICE AUTOMATION',intro:'Zenith can integrate compatible voice assistants into your smart-home environment for supported commands and routines.',cards:['“Alexa, good morning.”','“Alexa, movie mode.”','“Alexa, lock the front door.”']},
  products:{title:'The building blocks of a smarter home.',kicker:'PRODUCTS',intro:'A considered selection of smart switches, locks, panels, cameras, sensors and automation devices. Request installation to find the right fit.',cards:['Smart switches','Climate control panels','Smart door locks'],items:[
    {title:'Smart door locks',image:'/images/products/smart-lock.png',href:'/products/smart-door-locks',alt:'Premium black smart door lock with fingerprint reader'},
    {title:'Voice assistant pods',image:'/images/products/voice-pod.png',href:'/products/voice-assistant',alt:'White voice assistant pod with a soft cyan light ring'},
    {title:'Climate control panels',image:'/images/products/climate-panel.png',href:'/products/control-panels',alt:'Black air-conditioning control panel on a white wall'},
    {title:'Video doorbells',image:'/images/products/video-doorbell.png',href:'/products/video-doorbells',alt:'Matte black video doorbell beside a timber front door'},
  ]},
  projects:{title:'Smart spaces by Zenith.',kicker:'PROJECTS',intro:'A growing portfolio of connected environments. Sample concepts are shown here until completed Zenith projects are supplied.',cards:['Modern Residence · Concept','Apartment Development · Concept','Boutique Hotel · Concept']},
  developers:{title:'Build smart from the beginning.',kicker:'DEVELOPERS & ARCHITECTS',intro:'Zenith works with developers, architects, interior designers, construction companies and hospitality groups to integrate technology from the planning stage.',cards:['Property developers','Architects & interiors','Hospitality groups']},
  about:{title:'Integration is the difference.',kicker:'WHY ZENITH',intro:'Technology is easy. The value is in making it work together, beautifully and reliably, around the people who use it.',cards:['Integrated systems','Professional installation','Local support']},
  contact:{title:'Let’s design what comes next.',kicker:'CONSULTATION',intro:'Tell us about your property and the way you want it to feel. We’ll help shape the right smart-home solution.',cards:['Home','Apartment','Office / development']},
};

export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug:[slug]}))}

export default async function Page({params}:{params:Promise<{slug:string[]}>}){
  const {slug}=await params;const key=slug?.[0]||'solutions';const page=pages[key]||pages.solutions;
  return <main><header className="nav scrolled"><div className="container nav-inner"><Link href="/" className="wordmark">ZENITH<small>Technologies · Zimbabwe</small></Link><nav className="links"><Link href="/solutions">Solutions</Link><Link href="/smart-home">Smart Home</Link><Link href="/security">Security</Link><Link href="/products">Products</Link><Link href="/projects">Projects</Link><Link href="/about">About</Link></nav><Link className="button primary" href="/contact">Book a Consultation</Link></div></header><section className="detail-hero"><div className="container"><span className="eyebrow">{page.kicker}</span><h1 className="font-display">{page.title}</h1></div></section><section className="detail-body"><div className="container"><p>{page.intro}</p>{page.items?<div className="product-grid">{page.items.map((item,i)=><Link className="product-card" href={item.href} key={item.href}><div className="product-card-media"><Image src={item.image} alt={item.alt} width={800} height={900}/></div><div className="product-card-copy"><span className="eyebrow" style={{color:'#008fca'}}>0{i+1}</span><h3>{item.title}</h3><span className="product-card-link">View product →</span></div></Link>)}</div>:<div className="cards">{page.cards.map((x,i)=><div className="card" key={x}><span className="eyebrow" style={{color:'#008fca'}}>0{i+1}</span><h3>{x}</h3><p style={{fontSize:'.9rem',marginTop:10}}>{key==='contact'?'Tell us what you are planning and we will respond with the next step.':'Designed to work with the rest of your connected environment.'}</p></div>)}</div>}<div style={{marginTop:50,display:'flex',gap:12,flexWrap:'wrap'}}><Link href="/contact" className="button primary">{key==='contact'?'Request consultation':'Talk to Zenith'} →</Link><Link href="/" className="button">Back to home</Link></div></div></section><footer><div className="container"><div className="footer-bottom" style={{marginTop:0}}><span>© 2026 Zenith Technologies</span><span>Harare, Zimbabwe · Smart living, thoughtfully connected.</span></div></div></footer></main>
}
